<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

  <key>fileTypes</key>
  <array>
    <string>ts</string>
  </array>

  <key>name</key>
  <string>TypeScript</string>

  <key>scopeName</key>
  <string>source.ts</string>

  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#default</string>
    </dict>
  </array>

  <key>repository</key>
  <dict>

    <key>line-comment</key>
    <dict>
      <key>match</key>
      <string>(//).*$\n?</string>
      <key>name</key>
      <string>comment.line.ts</string>
    </dict>

    <key>block-comment</key>
    <dict>
      <key>begin</key>
      <string>/\*</string>
      <key>end</key>
      <string>\*/</string>
      <key>name</key>
      <string>comment.block.ts</string>
    </dict>

    <!-- Note: this only includes safe keywords that don't define new symbols -->
    <key>keyword</key>
    <dict>
      <key>match</key>
      <string>\b(?:private|public|static|export|declare|instanceof|is|typeof|new|delete|break|continue|return|throw|try|catch|finalize|if|else|while|do|with|for|in|switch|case|default)\b</string>
      <key>name</key>
      <string>keyword.ts</string>
    </dict>

    <key>operator</key>
    <dict>
      <key>match</key>
      <string>[+\-*/=&lt;&gt;&amp;|^!]</string>
      <key>name</key>
      <string>keyword.operator.ts</string>
    </dict>

    <key>constant</key>
    <dict>
      <key>match</key>
      <string>\b(?:this|null|super|true|false|NaN|Infinity|undefined)\b</string>
      <key>name</key>
      <string>constant.language.ts</string>
    </dict>

    <key>single-string</key>
    <dict>
      <key>begin</key>
      <string>'</string>
      <key>end</key>
      <string>'</string>
      <key>name</key>
      <string>string.quoted.ts</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(u\h{4}|x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.ts</string>
        </dict>
      </array>
    </dict>

    <key>double-string</key>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.ts</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(u\h{4}|x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.ts</string>
        </dict>
      </array>
    </dict>

    <key>number</key>
    <dict>
      <key>match</key>
      <string>\b(?:0[xX]\d*|\d+|\d+\.|\.\d+|\d+\.\d+)(?:[eE][+-]?\d+)?\b</string>
      <key>name</key>
      <string>constant.language.ts</string>
    </dict>

    <key>one-argument-lambda</key>
    <dict>
      <key>match</key>
      <string>([\w$]+)\s*(=&gt;)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.ts</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
    </dict>

    <key>simple</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#number</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#single-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#double-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#constant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#one-argument-lambda</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#extends-implements</string>
        </dict>
      </array>
    </dict>

    <key>import</key>
    <dict>
      <key>begin</key>
      <string>\b(import)\s+([\w$]+)\s*(=)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.ts</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>var</key>
    <dict>
      <key>begin</key>
      <string>\b(var)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?:;|(?=\bin\b))</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[\w$]+</string>
          <key>name</key>
          <string>entity.name.function.ts</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#colon-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#equals-value</string>
        </dict>
      </array>
    </dict>

    <key>colon-type</key>
    <dict>
      <key>begin</key>
      <string>:(\s*\{)?</string>
      <key>end</key>
      <string>(?=[,;{)]|=(?!&gt;))</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>equals-value</key>
    <dict>
      <key>begin</key>
      <string>=</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=[,;)])</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#default</string>
        </dict>
      </array>
    </dict>

    <key>extends-implements</key>
    <dict>
      <key>begin</key>
      <string>\b(extends|implements)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=[;{&gt;]|\bextends\b|\bimplements\b)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>module</key>
    <dict>
      <key>begin</key>
      <string>\b(module)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brace-body</string>
        </dict>
      </array>
    </dict>

    <key>class-interface</key>
    <dict>
      <key>begin</key>
      <string>\b(class|interface)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#class-interface-body</string>
        </dict>
      </array>
    </dict>

    <key>class-interface-body</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>(?=\})</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#class-interface-symbol</string>
        </dict>
      </array>
    </dict>

    <key>class-interface-symbol</key>
    <dict>
      <key>begin</key>
      <string>([\w$]+)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>[;}]</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#argument-list</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#colon-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#equals-value</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brace-body</string>
        </dict>
      </array>
    </dict>

    <key>argument-list</key>
    <dict>
      <key>begin</key>
      <string>\(</string>
      <key>end</key>
      <string>\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-simple-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#colon-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#equals-value</string>
        </dict>
      </array>
    </dict>

    <key>enum</key>
    <dict>
      <key>begin</key>
      <string>\b(enum)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#enum-body</string>
        </dict>
      </array>
    </dict>

    <key>enum-body</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>(?=\})</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#equals-value</string>
        </dict>
      </array>
    </dict>

    <key>function</key>
    <dict>
      <key>begin</key>
      <string>\b(function)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#colon-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#argument-list</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brace-body</string>
        </dict>
      </array>
    </dict>

    <key>define-generic-name</key>
    <dict>
      <key>begin</key>
      <string>([\w$]+)\s*&lt;</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>&gt;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#extends-implements</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>define-simple-name</key>
    <dict>
      <key>match</key>
      <string>[\w$]+</string>
      <key>name</key>
      <string>entity.name.function.ts</string>
    </dict>

    <key>define-name</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#define-generic-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define-simple-name</string>
        </dict>
      </array>
    </dict>

    <key>type-generic-name</key>
    <dict>
      <key>begin</key>
      <string>([\w$]+)\s*&lt;</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.ts</string>
        </dict>
      </dict>
      <key>end</key>
      <string>&gt;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#line-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#extends-implements</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>type-simple-name</key>
    <dict>
      <key>match</key>
      <string>[\w$]+</string>
      <key>name</key>
      <string>storage.type.ts</string>
    </dict>

    <key>type-name</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-generic-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-simple-name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name-parentheses</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name-braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type-name-brackets</string>
        </dict>
      </array>
    </dict>

    <key>type-name-parentheses</key>
    <dict>
      <key>begin</key>
      <string>\(</string>
      <key>end</key>
      <string>\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>type-name-braces</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>type-name-brackets</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>end</key>
      <string>\]</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-name</string>
        </dict>
      </array>
    </dict>

    <key>brace-body</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>(?=\})</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#default</string>
        </dict>
      </array>
    </dict>

    <key>parentheses</key>
    <dict>
      <key>begin</key>
      <string>\(</string>
      <key>end</key>
      <string>\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#default</string>
        </dict>
      </array>
    </dict>

    <key>braces</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#default</string>
        </dict>
      </array>
    </dict>

    <key>brackets</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>end</key>
      <string>\]</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#default</string>
        </dict>
      </array>
    </dict>

    <key>default</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#simple</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#var</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#import</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#module</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#class-interface</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#enum</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#function</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#parentheses</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brackets</string>
        </dict>
      </array>
    </dict>

  </dict>

</dict>
</plist>
